/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dto.Usuario;
import tablas.Cargo;
import funciones.Funciones;
import funciones.FuncionesUsuarios;
import java.awt.Window;
import java.util.List;
import java.util.Objects;
import javax.swing.SwingUtilities;
import static vo.CargoVO.CARGO_ADMIN;
import static vo.CargoVO.CARGO_USER;

/**
 *
 * @author shofy
 */
public class AgregarUsuarioCecrea extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    private Long idUsuario;
    
    public AgregarUsuarioCecrea() {
        initComponents();
        ActualizarUsuario.setVisible(false);
        cargo.removeAllItems();
        List<Cargo> cargos = Funciones.llenarComboCargo();
        cargos.forEach(c -> {cargo.addItem(c);});
    }

    public AgregarUsuarioCecrea(Long idusuario) {
        this();
        Usuario usuario = FuncionesUsuarios.buscarUsuarioPorId(idusuario);
        llenarCajas(usuario);
        Registrarusuario.setVisible(false);
        ActualizarUsuario.setVisible(true);        
        this.idUsuario = idusuario;
    }

    private void llenarCajas(Usuario usuario) {
        nomuser.setText(usuario.getNombre());
        conatctouser.setText(usuario.getContacto());
        rutuser.setText(usuario.getRutusuario());
        contraseñauser.setText(usuario.getContraseña());

        Cargo item;
        for (int i = 0; i < cargo.getItemCount(); i++) {
            item = (Cargo) cargo.getItemAt(i);
            if (Objects.equals(item.getId(), usuario.getIdCargo())) {
                cargo.setSelectedIndex(i);
            }
        }

    }

    private void limpiarcajas() {
        conatctouser.setText(null);
        nomuser.setText(null);
        rutuser.setText(null);
        contraseñauser.setText(null);
        cargo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jLabel1 = new javax.swing.JLabel();
        conatctouser = new javax.swing.JTextField();
        rutuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomuser = new javax.swing.JTextField();
        contraseñauser = new javax.swing.JTextField();
        Registrarusuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<Cargo>();
        ActualizarUsuario = new javax.swing.JButton();
        CerrarAgregarUsuario = new javax.swing.JButton();

        jLabel6.setText("CONTRASEÑA");

        setBackground(new java.awt.Color(0, 153, 255));
        setPreferredSize(new java.awt.Dimension(499, 401));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NOMBRE ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CONTACTO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CONTRASEÑA");

        jLabel4.setBackground(new java.awt.Color(51, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Registro de Usuarios Sistema Interno Cecrea La Ligua");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("RUT ");

        nomuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomuserActionPerformed(evt);
            }
        });

        Registrarusuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Registrarusuario.setText("Registrar usuario");
        Registrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarusuarioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CARGO");

        ActualizarUsuario.setText("Actualizar Usuario");
        ActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarUsuarioActionPerformed(evt);
            }
        });

        CerrarAgregarUsuario.setText("CERRAR");
        CerrarAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarAgregarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomuser)
                    .addComponent(rutuser)
                    .addComponent(conatctouser)
                    .addComponent(contraseñauser, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(cargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ActualizarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registrarusuario)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CerrarAgregarUsuario)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CerrarAgregarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(nomuser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rutuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(conatctouser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contraseñauser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrarusuario)
                    .addComponent(ActualizarUsuario))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarusuarioActionPerformed

        String name = nomuser.getText();
        String rut = rutuser.getText();
        String contacto = conatctouser.getText();
        String contraseña = contraseñauser.getText();
        int lab = cargo.getSelectedIndex();

        Funciones.validarRut(rut);
        Funciones.registrarUsuarios(name, rut, contacto, contraseña, lab);

        limpiarcajas();

        nomuser.requestFocus();
    }//GEN-LAST:event_RegistrarusuarioActionPerformed

    private void nomuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomuserActionPerformed

    private void ActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarUsuarioActionPerformed
        Usuario usuario = Usuario.builder()
                .nombre(nomuser.getText())
                .Rutusuario(rutuser.getText())
                .contacto(conatctouser.getText())
                .contraseña(contraseñauser.getText())
                .idCargo(((Cargo) cargo.getSelectedItem()).getId())
                .build();
        Funciones.actualizarusuario(this.idUsuario, usuario);
    }//GEN-LAST:event_ActualizarUsuarioActionPerformed

    private void CerrarAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarAgregarUsuarioActionPerformed
         Window w = SwingUtilities.getWindowAncestor(AgregarUsuarioCecrea.this);
        w.setVisible(false);
        
    }//GEN-LAST:event_CerrarAgregarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarUsuario;
    private javax.swing.JButton CerrarAgregarUsuario;
    private javax.swing.JButton Registrarusuario;
    private javax.swing.JComboBox<Cargo> cargo;
    private javax.swing.JTextField conatctouser;
    private javax.swing.JTextField contraseñauser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JTextField nomuser;
    private javax.swing.JTextField rutuser;
    // End of variables declaration//GEN-END:variables
}
